import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";
import Nav from "@/components/nav";
import PageWrapper from "@/components/page-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link
            href="https://fonts.cdnfonts.com/css/pp-neue-montreal"
            rel="stylesheet"
          />
        </head>
        <body className="antialiased">
          <PageWrapper>
            <div className="u-container u-gap flex min-h-screen flex-col">
              <Nav />
              <main className="flex flex-1 flex-col">{children}</main>
            </div>
          </PageWrapper>
        </body>
      </html>
    </ViewTransitions>
  );
}
