import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <head>
          <link
            href="https://fonts.cdnfonts.com/css/pp-neue-montreal"
            rel="stylesheet"
          />
        </head>
        <body className={"antialiased"}>{children}</body>
      </html>
    </ViewTransitions>
  );
}
